import { BusinessConfig } from '../../types/business';

export const softwareTemplate: BusinessConfig = {
  id: 'template-software',
  name: 'Nexa Digital Studio',
  industry: 'Jasa Pembuatan Website, Aplikasi & Software',
  tagline: 'Bangun Produk Digital yang Cepat, Profesional, dan Siap Berkembang',
  heroHeadline: 'Jasa Pembuatan Website, Aplikasi & Software untuk Bisnis',
  heroDescription: 'Kami membantu UMKM, startup, dan perusahaan membangun website, aplikasi mobile, dan software custom yang modern, cepat, aman, dan mudah dikembangkan.',
  primaryCtaText: 'Konsultasi Gratis',
  secondaryCtaText: 'Lihat Layanan',
  heroImageUrl: 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1400&q=85',
  aboutImageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1000&q=85',
  ctaBannerImageUrl: 'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=85',
  sections: { stats: true, about: true, services: true, pricing: true, whyChooseUs: true, gallery: true, testimonials: true, process: true, faq: true, location: true, cta: true },
  theme: {
    primaryColor: '#4F46E5', primaryHover: '#4338CA', secondaryColor: '#0F172A', accentColor: '#06B6D4',
    backgroundColor: '#F8FAFC', surfaceColor: '#FFFFFF', textColor: '#0F172A', mutedTextColor: '#64748B',
    borderRadius: '1rem', whatsappColor: '#25D366', heroVariant: 'split', fontOptionId: 'plus-jakarta',
    fontFamily: "'Plus Jakarta Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif",
  },
  seo: {
    title: 'Nexa Digital Studio - Jasa Pembuatan Website, Aplikasi & Software',
    description: 'Jasa pembuatan website, aplikasi Android/iOS, web app, sistem informasi, dan software custom untuk bisnis.',
    keywords: ['jasa pembuatan website', 'jasa pembuatan aplikasi', 'software house', 'web app development', 'aplikasi custom', 'sistem informasi'],
    ogImage: 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1400&q=85',
    canonicalUrl: 'https://nexadigitalstudio.com', schemaType: 'LocalBusiness',
  },
  contact: {
    phone: '0812-9000-1122', whatsappNumber: '6281290001122', email: 'hello@nexadigitalstudio.com',
    address: 'Jl. Digital Innovation No. 18', city: 'Bandung', province: 'Jawa Barat', postalCode: '40132',
    googleMapsUrl: 'https://maps.google.com/?q=Bandung',
    defaultWhatsAppMessage: 'Halo Nexa Digital Studio, saya ingin konsultasi kebutuhan website/aplikasi/software.',
  },
  aboutText: {
    p1: 'Nexa Digital Studio adalah partner teknologi untuk bisnis yang ingin membangun atau meningkatkan produk digital. Kami menggabungkan strategi, desain UI/UX, development, dan quality assurance dalam satu alur kerja.',
    p2: 'Setiap project dimulai dari memahami masalah bisnis, membuat scope yang jelas, lalu mengembangkan solusi yang dapat dipakai dan dikembangkan secara bertahap.',
    highlights: ['Konsultasi kebutuhan bisnis', 'UI/UX modern dan responsif', 'Development dengan teknologi modern', 'Source code dan dokumentasi jelas'],
    experienceYears: 5,
  },
  statistics: [
    { id: 'sd-stat-1', value: '50+', label: 'Project Digital' },
    { id: 'sd-stat-2', value: '5+', label: 'Tahun Pengalaman' },
    { id: 'sd-stat-3', value: '98%', label: 'Project Selesai' },
    { id: 'sd-stat-4', value: '4.9 ★', label: 'Rating Klien' },
  ],
  services: [
    { id: 'sd-service-1', name: 'Website Company Profile', category: 'Website', description: 'Website profesional untuk meningkatkan kredibilitas bisnis, menampilkan layanan, portfolio, kontak, dan CTA WhatsApp.', startingPrice: 1500000, priceNote: 'Mulai dari', duration: '5–10 hari kerja', iconName: 'Globe', popular: true, features: ['Responsive mobile', 'SEO basic', 'WhatsApp CTA', 'Deploy & domain guidance'], bookingMessage: 'Halo Nexa Digital Studio, saya ingin membuat website company profile.' },
    { id: 'sd-service-2', name: 'Web App / Sistem Informasi', category: 'Software', description: 'Aplikasi berbasis web untuk operasional seperti dashboard, inventory, booking, CRM, POS, dan sistem internal.', startingPrice: 5000000, priceNote: 'Mulai dari', duration: '2–6 minggu', iconName: 'LayoutDashboard', popular: true, features: ['Requirement analysis', 'UI/UX', 'Role & permission', 'Database & deployment'], bookingMessage: 'Halo Nexa Digital Studio, saya ingin konsultasi web app atau sistem informasi.' },
    { id: 'sd-service-3', name: 'Aplikasi Mobile Android & iOS', category: 'Mobile App', description: 'Pengembangan aplikasi mobile untuk pelanggan, marketplace internal, booking, membership, atau kebutuhan bisnis khusus.', startingPrice: 10000000, priceNote: 'Mulai dari', duration: '4–10 minggu', iconName: 'Smartphone', popular: false, features: ['Android & iOS strategy', 'UI/UX mobile', 'API integration', 'Testing & release guidance'], bookingMessage: 'Halo Nexa Digital Studio, saya ingin membuat aplikasi mobile.' },
    { id: 'sd-service-4', name: 'Custom Software', category: 'Custom', description: 'Software yang dirancang mengikuti alur bisnis Anda, termasuk integrasi API, payment gateway, laporan, dan automation.', startingPrice: 8000000, priceNote: 'Mulai dari', duration: '4–12 minggu', iconName: 'Code2', popular: false, features: ['Business workflow', 'Custom database', 'Third-party integration', 'Maintenance option'], bookingMessage: 'Halo Nexa Digital Studio, saya ingin membuat software custom.' },
    { id: 'sd-service-5', name: 'UI/UX & Prototype', category: 'Design', description: 'Perancangan user flow, wireframe, high-fidelity UI, dan prototype sebelum development dimulai.', startingPrice: 1000000, priceNote: 'Mulai dari', duration: '3–7 hari kerja', iconName: 'Palette', popular: false, features: ['User flow', 'Wireframe', 'High fidelity UI', 'Prototype'], bookingMessage: 'Halo Nexa Digital Studio, saya ingin konsultasi desain UI/UX.' },
  ],
  pricingPackages: [
    { id: 'sd-price-1', name: 'Starter Website', tagline: 'Untuk UMKM yang ingin mulai tampil profesional di internet.', price: 1500000, period: 'project', popular: false, features: [{ text: 'Company profile hingga 5 section', included: true }, { text: 'Responsive mobile', included: true }, { text: 'CTA WhatsApp', included: true }, { text: 'SEO basic', included: true }, { text: 'Admin panel', included: false }], bookingMessage: 'Halo Nexa Digital Studio, saya tertarik paket Starter Website.' },
    { id: 'sd-price-2', name: 'Business Web App', tagline: 'Untuk bisnis yang membutuhkan sistem operasional berbasis web.', price: 7500000, period: 'project', popular: true, badge: 'Paling Populer', features: [{ text: 'Requirement & flow analysis', included: true }, { text: 'UI/UX custom', included: true }, { text: 'Dashboard admin', included: true }, { text: 'Database & authentication', included: true }, { text: 'Deployment assistance', included: true }], bookingMessage: 'Halo Nexa Digital Studio, saya tertarik paket Business Web App.' },
    { id: 'sd-price-3', name: 'Custom Product', tagline: 'Untuk startup atau perusahaan dengan kebutuhan digital yang kompleks.', price: 15000000, period: 'project mulai', popular: false, features: [{ text: 'Discovery & technical planning', included: true }, { text: 'Custom UI/UX', included: true }, { text: 'Web/mobile development', included: true }, { text: 'API & third-party integration', included: true }, { text: 'Maintenance plan', included: true }], bookingMessage: 'Halo Nexa Digital Studio, saya ingin konsultasi paket Custom Product.' },
  ],
  whyChooseUs: [
    { id: 'sd-why-1', title: 'Berorientasi pada Bisnis', description: 'Kami tidak hanya membuat tampilan, tetapi menerjemahkan kebutuhan bisnis menjadi solusi digital.', iconName: 'Target' },
    { id: 'sd-why-2', title: 'Scope Transparan', description: 'Fitur, milestone, estimasi, dan biaya dibahas sejak awal agar project lebih terkontrol.', iconName: 'CheckCircle' },
    { id: 'sd-why-3', title: 'Teknologi Modern', description: 'Menggunakan stack modern yang maintainable dan siap dikembangkan.', iconName: 'Code2' },
    { id: 'sd-why-4', title: 'Siap Maintenance', description: 'Tersedia opsi maintenance dan pengembangan lanjutan setelah project selesai.', iconName: 'ShieldCheck' },
  ],
  gallery: [
    { id: 'sd-gallery-1', title: 'Dashboard Bisnis', category: 'Web App', imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1200&q=85', description: 'Contoh dashboard data dan operasional bisnis.' },
    { id: 'sd-gallery-2', title: 'UI/UX Product', category: 'Design', imageUrl: 'https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&w=1200&q=85', description: 'Eksplorasi interface untuk produk digital.' },
    { id: 'sd-gallery-3', title: 'Website Marketing', category: 'Website', imageUrl: 'https://images.unsplash.com/photo-1467232004584-a241de8bcf5d?auto=format&fit=crop&w=1200&q=85', description: 'Website modern untuk kebutuhan marketing.' },
    { id: 'sd-gallery-4', title: 'Team Development', category: 'Process', imageUrl: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=85', description: 'Kolaborasi tim dalam proses pengembangan produk.' },
  ],
  testimonials: [
    { id: 'sd-test-1', name: 'Fajar Pratama', roleOrVehicle: 'Owner UMKM', rating: 5, comment: 'Dibantu dari awal menentukan fitur sampai website online. Komunikasinya jelas dan hasilnya sesuai kebutuhan.', avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80' },
    { id: 'sd-test-2', name: 'Dina Maharani', roleOrVehicle: 'Startup Founder', rating: 5, comment: 'UI-nya modern dan timnya mau berdiskusi tentang alur bisnis, bukan hanya mengerjakan desain.', avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80' },
    { id: 'sd-test-3', name: 'Rizal Hidayat', roleOrVehicle: 'Business Owner', rating: 5, comment: 'Scope dan milestone cukup jelas sehingga kami bisa menyiapkan budget dan materi project dengan lebih baik.', avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=150&q=80' },
  ],
  process: [
    { step: 1, title: 'Konsultasi', description: 'Bahas masalah bisnis, target pengguna, fitur, dan tujuan project.', iconName: 'MessageCircle' },
    { step: 2, title: 'Discovery & Scope', description: 'Susun requirement, prioritas fitur, timeline, dan estimasi biaya.', iconName: 'FileText' },
    { step: 3, title: 'UI/UX Design', description: 'Buat user flow, wireframe, dan desain interface sebelum coding.', iconName: 'Palette' },
    { step: 4, title: 'Development', description: 'Bangun frontend, backend, database, integrasi, dan fitur sesuai scope.', iconName: 'Code2' },
    { step: 5, title: 'Testing & Launch', description: 'Quality check, revisi, deployment, dan handover project.', iconName: 'Rocket' },
  ],
  faqs: [
    { id: 'sd-faq-1', question: 'Berapa lama membuat website?', answer: 'Website company profile sederhana umumnya dapat selesai sekitar 5–10 hari kerja setelah materi dan scope disepakati.', category: 'Website' },
    { id: 'sd-faq-2', question: 'Apakah bisa membuat aplikasi sesuai kebutuhan khusus?', answer: 'Bisa. Kami dapat membantu dari discovery, desain, development, integrasi API, sampai deployment.', category: 'Custom Software' },
    { id: 'sd-faq-3', question: 'Apakah ada admin panel?', answer: 'Ada untuk project yang membutuhkan pengelolaan konten atau operasional. Admin panel dapat dibuat sesuai role dan kebutuhan.', category: 'Feature' },
    { id: 'sd-faq-4', question: 'Apakah bisa maintenance setelah project selesai?', answer: 'Bisa. Tersedia opsi maintenance, bug fixing, monitoring, dan pengembangan fitur lanjutan.', category: 'Maintenance' },
  ],
  openingHours: [{ day: 'Senin - Jumat', hours: '09.00 - 17.00 WIB' }, { day: 'Sabtu', hours: '09.00 - 13.00 WIB' }, { day: 'Minggu', hours: 'Tutup', isClosed: true }],
  socialLinks: [{ platform: 'instagram', url: 'https://instagram.com', label: 'Instagram' }, { platform: 'linkedin' as any, url: 'https://linkedin.com', label: 'LinkedIn' }],
  locationSection: { badgeText: 'Kantor & Konsultasi', title: 'Diskusikan Project Digital Anda', description: 'Konsultasi dapat dilakukan secara online maupun langsung berdasarkan jadwal yang disepakati.', addressTitle: 'Office', hoursTitle: 'Jam Konsultasi', openTodayBadgeText: 'Open for consultation', supportTitle: 'Project Consultant', directionsButtonText: 'Buka Google Maps', askDirectionsButtonText: 'Chat via WhatsApp', askDirectionsMessage: 'Halo Nexa Digital Studio, saya ingin konsultasi project digital.' },
  ctaSection: { badgeText: 'Siap memulai project?', headline: 'Ubah ide bisnis Anda menjadi produk digital.', description: 'Ceritakan kebutuhan Anda. Kami bantu memetakan scope, fitur, dan langkah development yang paling masuk akal.', primaryButtonText: 'Konsultasi Gratis', secondaryButtonText: 'Lihat Layanan', disclaimerText: 'Estimasi awal tanpa biaya konsultasi.' },
  footerSection: { aboutText: 'Partner teknologi untuk website, aplikasi, dan software custom.', quickLinksTitle: 'Navigasi', servicesTitle: 'Layanan', contactTitle: 'Kontak', copyrightText: '© 2026 Nexa Digital Studio', badgeText: 'Digital Product Partner', taglineNote: 'Build better. Ship faster.' },
  hero: { layoutVariant: 'split', eyebrowText: 'DIGITAL PRODUCT STUDIO', badgeText: 'Partner Teknologi Bisnis', headline: 'Bangun Website, Aplikasi & Software yang Siap Dipakai', description: 'Solusi digital custom untuk UMKM, startup, dan perusahaan dengan proses yang transparan dari konsultasi sampai launch.', primaryCtaText: 'Konsultasi Gratis', secondaryCtaText: 'Lihat Layanan', trustBadgeText: 'Dipercaya bisnis yang ingin bertumbuh', trustPoints: ['Scope transparan', 'UI/UX modern', 'Support setelah launch'], showTrustPoints: true, showRatingPill: true, ratingValue: '4.9 / 5.0', ratingLabel: 'Rating klien', backgroundType: 'image-overlay', backgroundColor: '#F8FAFC', backgroundMode: 'light', gradientStyle: 'brand-glow', texture: 'mesh', textureOpacity: .04, showBackgroundImageOverlay: true, backgroundImageUrl: 'https://images.unsplash.com/photo-1551434678-e076c223a692?auto=format&fit=crop&w=1400&q=85', backgroundImageOpacity: .14, backgroundImageBlur: 'md', backgroundImageBlurPx: 8, backgroundBlur: 'none', backgroundBlurPx: 0, backgroundOverlayImageOpacity: .18, overlayColor: '#0F172A', overlayOpacity: .08 },
};
