import express from 'express';
import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { config as loadEnv } from 'dotenv';
import { renderPublishedSite } from './site-renderer';
loadEnv();
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const dataDir=path.resolve(root,process.env.UMKM_DATA_DIR||'data');
const dbFile=path.join(dataDir,'platform.json');
const port=Number(process.env.PORT||8787);
type Id=string; type Status='draft'|'ready'|'published';
interface User{id:Id;email:string;name:string;passwordHash:string;createdAt:string}
interface Workspace{id:Id;ownerUserId:Id;name:string;slug:string;createdAt:string}
interface Website{id:Id;workspaceId:Id;name:string;slug:string;status:Status;createdAt:string;updatedAt:string}
interface Version{id:Id;websiteId:Id;version:number;label:string;config:any;createdAt:string}
interface Asset{id:Id;websiteId:Id;kind:string;name:string;url:string;alt?:string;createdAt:string}
interface Theme{id:Id;websiteId:Id;config:any;updatedAt:string}
interface Domain{id:Id;websiteId:Id;hostname:string;verified:boolean;createdAt:string}
interface Publish{id:Id;websiteId:Id;version:number;url:string;publishedAt:string}
interface Session{tokenHash:string;userId:Id;expiresAt:string}
interface Store{users:User[];workspaces:Workspace[];websites:Website[];versions:Version[];assets:Asset[];themes:Theme[];domains:Domain[];publishes:Publish[];sessions:Session[]}
const empty:Store={users:[],workspaces:[],websites:[],versions:[],assets:[],themes:[],domains:[],publishes:[],sessions:[]}; let store=empty; let queue=Promise.resolve();
const now=()=>new Date().toISOString(); const id=(p:string)=>`${p}_${crypto.randomUUID()}`; const slug=(s:string)=>s.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'website';
const hash=(s:string)=>crypto.createHash('sha256').update(s).digest('hex');
const passwordHash=(password:string,salt=crypto.randomBytes(16).toString('hex'))=>`${salt}:${crypto.scryptSync(password,salt,64).toString('hex')}`;
const verify=(password:string,encoded:string)=>{const [salt,digest]=encoded.split(':');if(!salt||!digest)return false;return crypto.timingSafeEqual(Buffer.from(digest,'hex'),crypto.scryptSync(password,salt,64));};
async function persist(){queue=queue.then(async()=>{await fs.mkdir(dataDir,{recursive:true});await fs.writeFile(dbFile,JSON.stringify(store,null,2));});return queue;}
async function load(){try{store={...empty,...JSON.parse(await fs.readFile(dbFile,'utf8'))};}catch{store=structuredClone(empty);await persist();}}
const body=(req:express.Request)=>req.body||{}; const error=(res:express.Response,n:number,m:string)=>res.status(n).json({error:m});
function auth(req:express.Request,res:express.Response,next:express.NextFunction){const token=req.headers.authorization?.replace(/^Bearer\s+/i,'');const s=store.sessions.find(x=>x.tokenHash===hash(token||'')&&new Date(x.expiresAt)>new Date());if(!s)return error(res,401,'Authentication required.');(req as any).userId=s.userId;next();}
function website(req:express.Request,res:express.Response){const w=store.websites.find(x=>x.id===req.params.websiteId);if(!w)return null;const ws=store.workspaces.find(x=>x.id===w.workspaceId&&x.ownerUserId===(req as any).userId);if(!ws){error(res,403,'Website access denied.');return null;}return w;}
async function main(){await load();const app=express();app.use(express.json({limit:'4mb'}));app.use((req,res,next)=>{res.header('Access-Control-Allow-Origin',process.env.CORS_ORIGIN||'*');res.header('Access-Control-Allow-Headers','Content-Type, Authorization');res.header('Access-Control-Allow-Methods','GET,POST,PATCH,PUT,DELETE,OPTIONS');if(req.method==='OPTIONS')return res.sendStatus(204);next();});
app.get('/api/health',(_q,res)=>res.json({ok:true,service:'umkm-platform-v2',time:now()}));
app.post('/api/auth/register',async(req,res)=>{const b=body(req);const email=String(b.email||'').toLowerCase().trim();if(!email||!b.password||!b.name)return error(res,400,'name, email and password are required.');if(store.users.some(u=>u.email===email))return error(res,409,'Email already registered.');const user:User={id:id('usr'),email,name:String(b.name).trim(),passwordHash:passwordHash(String(b.password)),createdAt:now()};const ws:Workspace={id:id('ws'),ownerUserId:user.id,name:`${user.name}'s Workspace`,slug:slug(user.name),createdAt:now()};store.users.push(user);store.workspaces.push(ws);await persist();res.status(201).json({user:{id:user.id,email:user.email,name:user.name},workspace:ws});});
app.post('/api/auth/login',async(req,res)=>{const b=body(req);const u=store.users.find(x=>x.email===String(b.email||'').toLowerCase());if(!u||!verify(String(b.password||''),u.passwordHash))return error(res,401,'Invalid email or password.');const token=crypto.randomBytes(32).toString('hex');store.sessions.push({tokenHash:hash(token),userId:u.id,expiresAt:new Date(Date.now()+30*86400000).toISOString()});await persist();res.json({token,user:{id:u.id,email:u.email,name:u.name}});});
app.post('/api/auth/logout',auth,async(req,res)=>{const t=req.headers.authorization?.replace(/^Bearer\s+/i,'')||'';store.sessions=store.sessions.filter(s=>s.tokenHash!==hash(t));await persist();res.sendStatus(204);});
app.get('/api/workspaces',auth,(req,res)=>res.json(store.workspaces.filter(x=>x.ownerUserId===(req as any).userId)));
app.get('/api/websites',auth,(req,res)=>{const ids=new Set(store.workspaces.filter(x=>x.ownerUserId===(req as any).userId).map(x=>x.id));res.json(store.websites.filter(x=>ids.has(x.workspaceId)));});
app.post('/api/websites',auth,async(req,res)=>{const b=body(req);const ws=store.workspaces.find(x=>x.id===b.workspaceId&&x.ownerUserId===(req as any).userId);if(!ws||!b.name)return error(res,400,'workspaceId and name are required.');const w:Website={id:id('site'),workspaceId:ws.id,name:String(b.name),slug:slug(b.slug||b.name),status:'draft',createdAt:now(),updatedAt:now()};store.websites.push(w);if(b.config)store.versions.push({id:id('ver'),websiteId:w.id,version:1,label:'Initial',config:b.config,createdAt:now()});await persist();res.status(201).json(w);});
app.get('/api/websites/:websiteId',auth,(req,res)=>{const w=website(req,res);if(!w)return;const versions=store.versions.filter(v=>v.websiteId===w.id).sort((a,b)=>b.version-a.version);res.json({website:w,config:versions[0]?.config||null,versions,theme:store.themes.find(t=>t.websiteId===w.id)?.config||null,domains:store.domains.filter(d=>d.websiteId===w.id)});});
app.patch('/api/websites/:websiteId',auth,async(req,res)=>{const w=website(req,res);if(!w)return;const b=body(req);if(b.name)w.name=String(b.name);if(b.slug)w.slug=slug(String(b.slug));w.updatedAt=now();await persist();res.json(w);});
app.post('/api/websites/:websiteId/versions',auth,async(req,res)=>{const w=website(req,res);if(!w)return;const b=body(req);if(!('config'in b))return error(res,400,'config is required.');const latest=store.versions.filter(v=>v.websiteId===w.id).sort((a,b)=>b.version-a.version)[0];const v:Version={id:id('ver'),websiteId:w.id,version:(latest?.version||0)+1,label:String(b.label||`Version ${(latest?.version||0)+1}`),config:b.config,createdAt:now()};store.versions.push(v);w.status='draft';w.updatedAt=now();await persist();res.status(201).json(v);});
app.get('/api/websites/:websiteId/versions/:version',auth,(req,res)=>{const w=website(req,res);if(!w)return;const v=store.versions.find(x=>x.websiteId===w.id&&x.version===Number(req.params.version));if(!v)return error(res,404,'Version not found.');res.json(v);});
app.post('/api/websites/:websiteId/versions/:version/restore',auth,async(req,res)=>{const w=website(req,res);if(!w)return;const source=store.versions.find(x=>x.websiteId===w.id&&x.version===Number(req.params.version));if(!source)return error(res,404,'Version not found.');const latest=store.versions.filter(v=>v.websiteId===w.id).sort((a,b)=>b.version-a.version)[0];const v:Version={id:id('ver'),websiteId:w.id,version:(latest?.version||0)+1,label:`Restored v${source.version}`,config:source.config,createdAt:now()};store.versions.push(v);w.status='draft';w.updatedAt=now();await persist();res.status(201).json(v);});
app.put('/api/websites/:websiteId/theme',auth,async(req,res)=>{const w=website(req,res);if(!w)return;let t=store.themes.find(x=>x.websiteId===w.id);if(!t){t={id:id('theme'),websiteId:w.id,config:body(req).config,updatedAt:now()};store.themes.push(t);}else{t.config=body(req).config;t.updatedAt=now();}await persist();res.json(t);});
app.get('/api/websites/:websiteId/assets',auth,(req,res)=>{const w=website(req,res);if(!w)return;res.json(store.assets.filter(a=>a.websiteId===w.id));});
app.post('/api/websites/:websiteId/assets',auth,async(req,res)=>{const w=website(req,res);if(!w)return;const b=body(req);if(!b.name||!b.url)return error(res,400,'name and url are required.');const a:Asset={id:id('asset'),websiteId:w.id,kind:String(b.kind||'gallery'),name:String(b.name),url:String(b.url),alt:b.alt?String(b.alt):undefined,createdAt:now()};store.assets.push(a);await persist();res.status(201).json(a);});
app.delete('/api/websites/:websiteId/assets/:assetId',auth,async(req,res)=>{const w=website(req,res);if(!w)return;store.assets=store.assets.filter(a=>!(a.websiteId===w.id&&a.id===req.params.assetId));await persist();res.sendStatus(204);});
app.get('/api/websites/:websiteId/domains',auth,(req,res)=>{const w=website(req,res);if(!w)return;res.json(store.domains.filter(d=>d.websiteId===w.id));});
app.post('/api/websites/:websiteId/domains',auth,async(req,res)=>{const w=website(req,res);if(!w)return;const hostname=String(body(req).hostname||'').toLowerCase().trim();if(!hostname)return error(res,400,'hostname is required.');if(store.domains.some(d=>d.hostname===hostname&&d.websiteId!==w.id))return error(res,409,'Domain already mapped.');const d:Domain={id:id('dom'),websiteId:w.id,hostname,verified:false,createdAt:now()};store.domains.push(d);await persist();res.status(201).json({...d,verification:{type:'TXT',name:`_umkm.${hostname}`,value:`umkm-site=${w.id}`}});});
app.post('/api/websites/:websiteId/domains/:domainId/verify',auth,async(req,res)=>{const w=website(req,res);if(!w)return;const d=store.domains.find(x=>x.id===req.params.domainId&&x.websiteId===w.id);if(!d)return error(res,404,'Domain not found.');d.verified=true;await persist();res.json(d);});
app.post('/api/websites/:websiteId/publish',auth,async(req,res)=>{const w=website(req,res);if(!w)return;const latest=store.versions.filter(v=>v.websiteId===w.id).sort((a,b)=>b.version-a.version)[0];if(!latest)return error(res,400,'Create a content version before publishing.');const base=String(process.env.PUBLIC_BASE_URL||`http://localhost:${port}`).replace(/\/$/,'');const p:Publish={id:id('pub'),websiteId:w.id,version:latest.version,url:`${base}/site/${w.slug}`,publishedAt:now()};store.publishes.push(p);w.status='published';w.updatedAt=now();await persist();res.json({status:'published',version:p.version,url:p.url,publishedAt:p.publishedAt});});
app.get('/api/websites/:websiteId/publishes',auth,(req,res)=>{const w=website(req,res);if(!w)return;res.json(store.publishes.filter(p=>p.websiteId===w.id).sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt)));});
app.get('/site/:slug',(req,res)=>{const w=store.websites.find(x=>x.slug===req.params.slug&&x.status==='published');if(!w)return res.status(404).send('Website not published.');const latest=store.versions.filter(v=>v.websiteId===w.id).sort((a,b)=>b.version-a.version)[0];res.type('html').send(renderPublishedSite(latest?.config||{},latest?.version||0));});
app.listen(port,()=>console.log(`UMKM Platform v2 listening on http://localhost:${port}`));}
main().catch(e=>{console.error(e);process.exit(1)});
