import type { BusinessConfig } from '../src/types/business';

const escapeHtml = (value: unknown) => String(value ?? '').replace(/[&<>\"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '\"':'&quot;', "'":'&#39;' }[char] || char));
const money = (value:number) => new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value || 0);

export function renderPublishedSite(business: BusinessConfig, version:number) {
  const primary = escapeHtml(business.theme?.primaryColor || '#0f172a');
  const bg = escapeHtml(business.theme?.backgroundColor || '#f8fafc');
  const text = escapeHtml(business.theme?.textColor || '#0f172a');
  const heroImage = escapeHtml(business.hero?.backgroundImageUrl || business.heroImageUrl);
  const heroHeadline = escapeHtml(business.hero?.headline || business.heroHeadline);
  const heroDescription = escapeHtml(business.hero?.description || business.heroDescription);
  const services = business.services.map(item => `<article class="card"><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.description)}</p><strong>Mulai ${money(item.startingPrice)}</strong></article>`).join('');
  const testimonials = business.testimonials.slice(0,6).map(item => `<article class="quote"><strong>${escapeHtml(item.name)}</strong><span>${'★'.repeat(Math.max(0,Math.min(5,item.rating)))}</span><p>${escapeHtml(item.comment)}</p></article>`).join('');
  const faqs = business.faqs.slice(0,8).map(item => `<details><summary>${escapeHtml(item.question)}</summary><p>${escapeHtml(item.answer)}</p></details>`).join('');
  const gallery = business.gallery.slice(0,9).map(item => `<figure><img src="${escapeHtml(item.imageUrl)}" alt="${escapeHtml(item.title)}"><figcaption>${escapeHtml(item.title)}</figcaption></figure>`).join('');
  return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHtml(business.seo?.title || business.name)}</title><meta name="description" content="${escapeHtml(business.seo?.description || business.heroDescription)}"><meta name="generator" content="UMKM Website Engine"><style>
  *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:${bg};color:${text};font-family:Inter,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;line-height:1.6}a{text-decoration:none;color:inherit}.wrap{max-width:1120px;margin:auto;padding:0 24px}.nav{position:sticky;top:0;z-index:10;background:rgba(255,255,255,.88);backdrop-filter:blur(14px);border-bottom:1px solid #e2e8f0}.navin{height:68px;display:flex;align-items:center;justify-content:space-between;gap:20px}.brand{font-weight:900}.links{display:flex;gap:20px;font-size:13px;font-weight:700;color:#64748b}.hero{position:relative;overflow:hidden;min-height:600px;display:flex;align-items:center;background:#0f172a;color:white}.hero:before{content:"";position:absolute;inset:0;background-image:linear-gradient(120deg,rgba(2,6,23,.94),rgba(2,6,23,.45)),url('${heroImage}');background-size:cover;background-position:center;filter:saturate(.9)}.hero>*{position:relative}.hero .wrap{width:100%;padding-top:90px;padding-bottom:90px}.eyebrow{font-size:12px;font-weight:900;letter-spacing:.16em;text-transform:uppercase;color:${primary}}h1{font-size:clamp(42px,7vw,76px);line-height:1.02;letter-spacing:-.055em;max-width:820px;margin:18px 0}.lead{max-width:680px;color:#cbd5e1;font-size:18px}.btn{display:inline-flex;margin-top:28px;padding:13px 18px;border-radius:12px;background:${primary};color:white;font-weight:800;font-size:13px}.section{padding:86px 0}.section h2{font-size:36px;letter-spacing:-.04em;line-height:1.1;margin:0 0 10px}.muted{color:#64748b}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:30px}.card,.quote{padding:24px;border:1px solid #e2e8f0;border-radius:18px;background:white;box-shadow:0 10px 30px rgba(15,23,42,.04)}.card h3{margin:0 0 8px}.card p,.quote p{color:#64748b;font-size:14px}.card strong{font-size:13px}.gallery{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:28px}.gallery figure{margin:0;overflow:hidden;border-radius:18px;background:white;border:1px solid #e2e8f0}.gallery img{width:100%;height:220px;object-fit:cover;display:block}.gallery figcaption{padding:10px 12px;font-weight:800;font-size:12px}.faq{max-width:820px;margin-top:28px}.faq details{padding:18px 0;border-bottom:1px solid #e2e8f0}.faq summary{cursor:pointer;font-weight:800}.faq p{color:#64748b}.footer{padding:40px 0;border-top:1px solid #e2e8f0;color:#64748b;font-size:12px}.version{opacity:.5}@media(max-width:760px){.links{display:none}.grid,.gallery{grid-template-columns:1fr}.section{padding:60px 0}.hero{min-height:560px}.lead{font-size:16px}}
  </style></head><body><header class="nav"><div class="wrap navin"><div class="brand">${escapeHtml(business.name)}</div><nav class="links">${(business.navigation?.links||[]).slice(0,6).map(link=>`<a href="${escapeHtml(link.href)}">${escapeHtml(link.name)}</a>`).join('')}</nav><a class="btn" style="margin:0;padding:9px 13px" href="https://wa.me/${escapeHtml(business.contact.whatsappNumber)}">${escapeHtml(business.primaryCtaText)}</a></div></header><section class="hero"><div class="wrap"><div class="eyebrow">${escapeHtml(business.industry)}</div><h1>${heroHeadline}</h1><p class="lead">${heroDescription}</p><a class="btn" href="https://wa.me/${escapeHtml(business.contact.whatsappNumber)}?text=${encodeURIComponent(business.contact.defaultWhatsAppMessage)}">${escapeHtml(business.primaryCtaText)}</a></div></section><main><section class="section"><div class="wrap"><p class="eyebrow">Layanan</p><h2>Solusi untuk kebutuhan Anda</h2><p class="muted">Pilih layanan yang paling sesuai.</p><div class="grid">${services}</div></div></section>${testimonials?`<section class="section" style="background:#f1f5f9"><div class="wrap"><p class="eyebrow">Testimoni</p><h2>Dipercaya pelanggan</h2><div class="grid">${testimonials}</div></div></section>`:''}${gallery?`<section class="section"><div class="wrap"><p class="eyebrow">Galeri</p><h2>Aktivitas kami</h2><div class="gallery">${gallery}</div></div></section>`:''}${faqs?`<section class="section"><div class="wrap"><p class="eyebrow">FAQ</p><h2>Pertanyaan umum</h2><div class="faq">${faqs}</div></div></section>`:''}<section class="section" style="background:${primary};color:white"><div class="wrap"><h2 style="color:white">${escapeHtml(business.ctaSection?.headline || business.primaryCtaText)}</h2><p style="color:#e2e8f0">${escapeHtml(business.ctaSection?.description || business.heroDescription)}</p><a class="btn" style="background:white;color:${primary}" href="https://wa.me/${escapeHtml(business.contact.whatsappNumber)}?text=${encodeURIComponent(business.contact.defaultWhatsAppMessage)}">Hubungi via WhatsApp</a></div></section></main><footer class="footer"><div class="wrap"><strong>${escapeHtml(business.name)}</strong><p>${escapeHtml(business.contact.address)} · ${escapeHtml(business.contact.city)}, ${escapeHtml(business.contact.province)}</p><span class="version">Published version ${version}</span></div></footer></body></html>`;
}
