import { ServiceItem, PricingPackage } from '../types/business';

/**
 * Services Configuration
 * 
 * Each service automatically renders in the Services grid with its duration,
 * starting price in IDR, features, and custom WhatsApp booking message.
 */
export const servicesConfig: ServiceItem[] = [
  {
    id: 'servis-ringan',
    name: 'Servis Ringan / Berkala',
    category: 'Perawatan Rutin',
    description: 'Pembersihan filter udara, penyetelan celah katup/klep, pengecekan busi, rem depan belakang, kelistrikan, dan tekanan ban.',
    startingPrice: 45000,
    priceNote: 'Mulai dari (Jasa saja)',
    duration: '30 - 45 Menit',
    iconName: 'Wrench',
    popular: true,
    features: [
      'Pembersihan filter udara',
      'Penyetelan rem depan & belakang',
      'Pengecekan busi & kelistrikan',
      'Penyetelan rantai / roda',
      'Free cek angin nitrogen',
    ],
    bookingMessage: 'Halo Bengkel Jaya Motor, saya ingin booking servis ringan/berkala untuk motor saya.',
  },
  {
    id: 'servis-injeksi',
    name: 'Servis Lengkap & Kalibrasi Injeksi',
    category: 'Performa Mesin',
    description: 'Scanning ECU dengan scanner OBD modern, infus throttle body, pembersihan injector ultrasonik, reset throttle position sensor (TPS).',
    startingPrice: 85000,
    priceNote: 'Termasuk Chemical Cleaner',
    duration: '45 - 60 Menit',
    iconName: 'Gauge',
    popular: true,
    features: [
      'Scan ECU & Reset Sensor TPS',
      'Infus & Pembersihan Throttle Body',
      'Cek pengapian & injektor bahan bakar',
      'Penyetelan stasioner optimal',
      'Hasil tarikan lebih enteng & hemat BBM',
    ],
    bookingMessage: 'Halo Bengkel Jaya Motor, saya ingin reservasi servis lengkap dan scan injeksi.',
  },
  {
    id: 'ganti-oli',
    name: 'Ganti Oli Mesin & Transmisi',
    category: 'Pelumasan',
    description: 'Penggantian pelumas berkualitas 100% original sesuai standar pabrikan (AHM Oil, Yamalube, Motul, Shell Advance, Enduro).',
    startingPrice: 45000,
    priceNote: 'Tergantung merk oli',
    duration: '15 Menit',
    iconName: 'Droplets',
    popular: false,
    features: [
      'Oli dijamin 100% Original berbarcode',
      'Gratis jasa ganti oli',
      'Gratis semprot angin kompresor & cek rem',
      'Pengecekan oli gardan untuk motor matic',
    ],
    bookingMessage: 'Halo Bengkel Jaya Motor, saya ingin ganti oli mesin & cek motor.',
  },
  {
    id: 'servis-cvt-matic',
    name: 'Servis CVT Matic (Anti-Gredek)',
    category: 'Spesialis Matic',
    description: 'Pembersihan pulley, penggantian gemuk/grease CVT hi-temp, pengecekan v-belt, roller, per sentrifugal, dan mangkok kopling.',
    startingPrice: 50000,
    priceNote: 'Termasuk Grease Hi-Temp',
    duration: '40 - 50 Menit',
    iconName: 'Cog',
    popular: true,
    features: [
      'Bongkar & cuci bersih pulley CVT',
      'Pemberian grease CVT khusus tahan panas',
      'Hilangkan keluhan getar / gredek tarikan awal',
      'Pemeriksaan keausan v-belt & roller',
    ],
    bookingMessage: 'Halo Bengkel Jaya Motor, motor matic saya gredek/getar di tarikan awal, mau booking servis CVT.',
  },
  {
    id: 'ganti-sparepart',
    name: 'Penggantian Suku Cadang & Kaki-kaki',
    category: 'Komponen & Suku Cadang',
    description: 'Pemasangan kampas rem, ban luar/dalam, shockbreaker, rantai gir, laher roda, aki, dengan garansi pemasangan rapi dan presisi.',
    startingPrice: 35000,
    priceNote: 'Biaya jasa mulai',
    duration: '20 - 45 Menit',
    iconName: 'Cpu',
    popular: false,
    features: [
      'Pilihan sparepart OEM Original atau aftermarket berkualitas',
      'Pemasangan dengan kunci torsi presisi',
      'Sparepart lama rusak dikembalikan ke pemilik',
      'Garansi pemasangan tidak bunyi',
    ],
    bookingMessage: 'Halo Bengkel Jaya Motor, saya mau tanya stok dan harga penggantian suku cadang.',
  },
  {
    id: 'turun-mesin',
    name: 'Overhaul / Turun Mesin & Kelistrikan',
    category: 'Perbaikan Berat',
    description: 'Perbaikan komprehensif untuk mesin berasap putih/hitam, hilang kompresi, bunyi kasar stang seher/kruk as, dan kelistrikan konslet.',
    startingPrice: 250000,
    priceNote: 'Jasa bongkar pasang',
    duration: '1 - 3 Hari Kerja',
    iconName: 'Flame',
    popular: false,
    features: [
      'Pembersihan kerak ruang bakar menyeluruh',
      'Pengukuran kepresisian blok silinder & seher',
      'Skir klep & ganti sil klep bocor',
      'Garansi pengerjaan mesin hingga 30 hari',
    ],
    bookingMessage: 'Halo Bengkel Jaya Motor, saya ingin konsultasi kerusakan mesin berat / overhaul.',
  },
];

/**
 * Bundled Pricing Packages
 */
export const pricingConfig: PricingPackage[] = [
  {
    id: 'paket-hemat-rutin',
    name: 'Paket Hemat Rutin',
    tagline: 'Perawatan dasar bulanan agar motor tetap prima dan hemat bahan bakar.',
    price: 95000,
    originalPrice: 115000,
    period: 'per motor',
    popular: false,
    badge: 'Paling Praktis',
    features: [
      { text: 'Jasa Servis Ringan Berkala', included: true },
      { text: 'Oli Mesin Berkualitas Standar 0.8L', included: true },
      { text: 'Pengecekan Busi & Filter Udara', included: true },
      { text: 'Penyetelan Rem & Rantai', included: true },
      { text: 'Cek Kelistrikan & Lampu', included: true },
      { text: 'Servis CVT / Injeksi Scanning', included: false },
      { text: 'Garansi Servis 14 Hari', included: true },
    ],
    bookingMessage: 'Halo Bengkel Jaya Motor, saya mau pesan Paket Hemat Rutin seharga Rp 95.000.',
  },
  {
    id: 'paket-matic-anti-gredek',
    name: 'Paket Matic Segar Anti-Gredek',
    tagline: 'Solusi tuntas motor matic tarikan berat, getar saat start, dan boros bensin.',
    price: 165000,
    originalPrice: 195000,
    period: 'per motor',
    popular: true,
    badge: 'Paling Laris',
    features: [
      { text: 'Servis Ringan Mesin Komplit', included: true },
      { text: 'Oli Mesin Matic + Oli Gardan Original', included: true },
      { text: 'Bongkar & Servis CVT Menyeluruh', included: true },
      { text: 'Pemberian Grease CVT Hi-Temp', included: true },
      { text: 'Pembersihan Throttle Body Ringan', included: true },
      { text: 'Garansi Anti-Gredek 14 Hari', included: true },
      { text: 'Prioritas Antrean Servis', included: true },
    ],
    bookingMessage: 'Halo Bengkel Jaya Motor, saya mau ambil Paket Matic Segar Anti-Gredek seharga Rp 165.000.',
  },
  {
    id: 'paket-tune-up-injeksi',
    name: 'Paket Tune Up Super Injeksi',
    tagline: 'Restorasi performa mesin maksimal seperti baru keluar dari dealer.',
    price: 245000,
    originalPrice: 290000,
    period: 'per motor',
    popular: false,
    badge: 'Performa Maksimal',
    features: [
      { text: 'Servis Mesin Lengkap Komprehensif', included: true },
      { text: 'Oli Mesin Synthetic Berkualitas Tinggi', included: true },
      { text: 'Scan Komputer ECU & Kalibrasi TPS', included: true },
      { text: 'Infus Injektor + Cleaner Throttle Body', included: true },
      { text: 'Servis CVT Komplit (untuk motor matic)', included: true },
      { text: 'Pengecekan Kompresi & Tekanan Fuel Pump', included: true },
      { text: 'Garansi Servis Penuh 21 Hari', included: true },
    ],
    bookingMessage: 'Halo Bengkel Jaya Motor, saya mau booking Paket Tune Up Super Injeksi Rp 245.000.',
  },
];
