import React, { useState } from 'react';
import { BusinessConfig, HeroConfig, HeroLayoutVariant, ThemeConfig } from '../types/business';
import { templateList } from '../config/templates';
import { heroLayoutOptions, heroBackgroundOptions, heroGradientOptions, heroBackgroundPresets, heroVariantPresets } from '../config/hero';
import { Settings2, X, Check, Download, Copy, Sparkles, Palette, FileText, Menu, Search, BriefcaseBusiness, Image as ImageIcon, MapPin, MessageCircle, HelpCircle, LayoutTemplate, Plus, Trash2, RotateCcw, Store } from 'lucide-react';
import './dev-panel.css';

interface DevPanelProps { currentBusiness: BusinessConfig; onSelectBusiness: (business: BusinessConfig) => void; }
type Tab = 'business'|'theme'|'navigation'|'hero'|'seo'|'services'|'testimonials'|'gallery'|'faq'|'location'|'cta'|'footer';
type AnyRecord = Record<string, any>;

const groups = [
  { title:'Website & Brand', items:[['business','Business & Content',BriefcaseBusiness],['theme','Theme & Style',Palette],['navigation','Navigation',Menu],['hero','Hero',LayoutTemplate],['seo','SEO',Search]] },
  { title:'Sections & Content', items:[['services','Services & Pricing',BriefcaseBusiness],['testimonials','Testimonials',MessageCircle],['gallery','Gallery',ImageIcon],['faq','FAQ',HelpCircle],['location','Location',MapPin],['cta','CTA',MessageCircle],['footer','Footer',FileText]] },
] as const;
const configKeys: Record<Exclude<Tab,'business'>, keyof BusinessConfig> = { theme:'theme',navigation:'navigation',hero:'hero',seo:'seo',services:'services',testimonials:'testimonials',gallery:'gallery',faq:'faqs',location:'locationSection',cta:'ctaSection',footer:'footerSection' };
const businessFields = ['name','industry','tagline','heroHeadline','heroDescription','primaryCtaText','secondaryCtaText','heroImageUrl','aboutImageUrl','ctaBannerImageUrl','contact','aboutText','statistics','whyChooseUs','process','openingHours','socialLinks','sections'];
const labels: Record<string,string> = { business:'Business & Content',theme:'Theme & Style',navigation:'Navigation',hero:'Hero',seo:'SEO',services:'Services & Pricing',testimonials:'Testimonials',gallery:'Gallery',faq:'FAQ',location:'Location',cta:'CTA',footer:'Footer' };

const colorPalettes:{id:string;name:string;colors:Pick<ThemeConfig,'primaryColor'|'primaryHover'|'secondaryColor'|'accentColor'|'backgroundColor'|'surfaceColor'|'textColor'|'mutedTextColor'>}[]=[
 {id:'ember',name:'Ember',colors:{primaryColor:'#DC2626',primaryHover:'#B91C1C',secondaryColor:'#0F172A',accentColor:'#F59E0B',backgroundColor:'#F8FAFC',surfaceColor:'#FFFFFF',textColor:'#0F172A',mutedTextColor:'#64748B'}},
 {id:'ocean',name:'Ocean',colors:{primaryColor:'#0284C7',primaryHover:'#0369A1',secondaryColor:'#0F172A',accentColor:'#06B6D4',backgroundColor:'#F0F9FF',surfaceColor:'#FFFFFF',textColor:'#0F172A',mutedTextColor:'#64748B'}},
 {id:'emerald',name:'Emerald',colors:{primaryColor:'#059669',primaryHover:'#047857',secondaryColor:'#064E3B',accentColor:'#34D399',backgroundColor:'#F0FDF4',surfaceColor:'#FFFFFF',textColor:'#0F172A',mutedTextColor:'#64748B'}},
 {id:'violet',name:'Violet',colors:{primaryColor:'#7C3AED',primaryHover:'#6D28D9',secondaryColor:'#1E1B4B',accentColor:'#A78BFA',backgroundColor:'#F5F3FF',surfaceColor:'#FFFFFF',textColor:'#18181B',mutedTextColor:'#71717A'}},
 {id:'rose',name:'Rose',colors:{primaryColor:'#E11D48',primaryHover:'#BE123C',secondaryColor:'#4C0519',accentColor:'#FB7185',backgroundColor:'#FFF1F2',surfaceColor:'#FFFFFF',textColor:'#1F2937',mutedTextColor:'#6B7280'}},
 {id:'amber',name:'Amber',colors:{primaryColor:'#D97706',primaryHover:'#B45309',secondaryColor:'#292524',accentColor:'#FBBF24',backgroundColor:'#FFFBEB',surfaceColor:'#FFFFFF',textColor:'#1C1917',mutedTextColor:'#78716C'}},
 {id:'indigo',name:'Indigo',colors:{primaryColor:'#4F46E5',primaryHover:'#4338CA',secondaryColor:'#172554',accentColor:'#818CF8',backgroundColor:'#EEF2FF',surfaceColor:'#FFFFFF',textColor:'#111827',mutedTextColor:'#6B7280'}},
 {id:'teal',name:'Teal',colors:{primaryColor:'#0F766E',primaryHover:'#115E59',secondaryColor:'#134E4A',accentColor:'#2DD4BF',backgroundColor:'#F0FDFA',surfaceColor:'#FFFFFF',textColor:'#134E4A',mutedTextColor:'#64748B'}},
 {id:'slate',name:'Slate',colors:{primaryColor:'#475569',primaryHover:'#334155',secondaryColor:'#0F172A',accentColor:'#94A3B8',backgroundColor:'#F8FAFC',surfaceColor:'#FFFFFF',textColor:'#0F172A',mutedTextColor:'#64748B'}},
 {id:'luxury',name:'Luxury',colors:{primaryColor:'#A16207',primaryHover:'#854D0E',secondaryColor:'#18181B',accentColor:'#D4AF37',backgroundColor:'#FAFAF9',surfaceColor:'#FFFFFF',textColor:'#18181B',mutedTextColor:'#71717A'}},
];

function labelize(s:string){return s.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/[_-]/g,' ').replace(/\b\w/g,c=>c.toUpperCase());}
function isColor(v:any){return typeof v==='string' && /^#[0-9a-f]{3,8}$/i.test(v);}
function isUrl(k:string){return /url|image|logo|favicon/i.test(k);}
function isLong(k:string,v:string){return v.length>90 || /description|text|content|message|comment|answer|address/i.test(k);}
function setPath(root:any,path:string[],value:any):any{if(!path.length)return value;const c=Array.isArray(root)?[...root]:{...(root||{})};const[h,...r]=path;c[h]=r.length?setPath(c[h],r,value):value;return c;}
function delPath(root:any,path:string[]):any{if(!path.length)return root;const c=Array.isArray(root)?[...root]:{...(root||{})};const[h,...r]=path;if(!r.length){Array.isArray(c)?c.splice(Number(h),1):delete c[h];return c;}c[h]=delPath(c[h],r);return c;}
function emptyLike(v:any){if(typeof v==='string')return '';if(typeof v==='number')return 0;if(typeof v==='boolean')return false;if(Array.isArray(v))return [];if(v&&typeof v==='object')return Object.fromEntries(Object.entries(v).map(([k,x])=>[k,emptyLike(x)]));return '';}

function Field({label,value,path,onChange,onDelete,depth=0}:{label:string;value:any;path:string[];onChange:(p:string[],v:any)=>void;onDelete?:(p:string[])=>void;depth?:number}){
 if(Array.isArray(value)) return <div className="rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="mb-2 flex items-center justify-between"><b className="text-[10px] text-slate-700">{labelize(label)}</b><button type="button" onClick={()=>onChange(path,[...value,emptyLike(value[0]??'')])} className="rounded-lg border bg-white px-2 py-1.5 text-[9px] font-bold"><Plus className="mr-1 inline h-3 w-3"/>Tambah</button></div><div className="space-y-2">{value.map((item:any,i:number)=><div key={i} className="rounded-lg border bg-white p-2.5"><div className="mb-2 flex justify-between"><span className="text-[9px] font-bold uppercase tracking-wide text-slate-400">Item {i+1}</span><button type="button" onClick={()=>onDelete?.([...path,String(i)])} className="text-slate-400 hover:text-red-600"><Trash2 className="h-3 w-3"/></button></div><Field label={typeof item==='object'?label:`${label} ${i+1}`} value={item} path={[...path,String(i)]} onChange={onChange} onDelete={onDelete} depth={depth+1}/></div>)}</div></div>;
 if(value&&typeof value==='object') return <div className={depth?'space-y-2 border-l border-slate-200 pl-3':'space-y-2'}><b className="block text-[10px] font-bold text-slate-700">{labelize(label)}</b>{Object.entries(value).map(([k,v])=><Field key={k} label={k} value={v} path={[...path,k]} onChange={onChange} onDelete={onDelete} depth={depth+1}/>)}</div>;
 const sv=value==null?'':String(value);
 if(typeof value==='boolean') return <label className="flex items-center justify-between rounded-lg border bg-white px-3 py-2.5"><span className="text-[10px] font-semibold text-slate-700">{labelize(label)}</span><button type="button" onClick={()=>onChange(path,!value)} className={`h-5 w-9 rounded-full ${value?'bg-slate-900':'bg-slate-200'}`}><span className={`block h-4 w-4 rounded-full bg-white transition ${value?'translate-x-4':'translate-x-0.5'}`}/></button></label>;
 if(isColor(value)) return <label className="dev-panel-field"><span className="dev-panel-field-label">{labelize(label)}</span><div className="flex gap-2"><input type="color" value={sv.length===7?sv:'#000000'} onChange={e=>onChange(path,e.target.value)} className="h-9 w-11 rounded-lg border border-slate-200 bg-white p-0.5"/><input value={sv} onChange={e=>onChange(path,e.target.value)} className="dev-panel-input font-mono"/></div></label>;
 if(typeof value==='number') return <label className="dev-panel-field"><span className="dev-panel-field-label">{labelize(label)}</span><input type="number" value={value} onChange={e=>onChange(path,Number(e.target.value))} className="dev-panel-input"/></label>;
 if(isUrl(label)) return <label className="dev-panel-field"><span className="dev-panel-field-label">{labelize(label)}</span><input type="url" value={sv} onChange={e=>onChange(path,e.target.value)} placeholder="https://..." className="dev-panel-input"/></label>;
 if(isLong(label,sv)) return <label className="dev-panel-field"><span className="dev-panel-field-label">{labelize(label)}</span><textarea value={sv} onChange={e=>onChange(path,e.target.value)} rows={3} className="dev-panel-input dev-panel-textarea"/></label>;
 return <label className="dev-panel-field"><span className="dev-panel-field-label">{labelize(label)}</span><input value={sv} onChange={e=>onChange(path,e.target.value)} className="dev-panel-input"/></label>;
}

function ThemeEditor({theme,onChange}:{theme:ThemeConfig;onChange:(theme:ThemeConfig)=>void}){
 const applyPalette=(palette:typeof colorPalettes[number])=>onChange({...theme,...palette.colors});
 return <div className="space-y-4">
  <section className="dev-panel-section"><div className="mb-1 flex items-center justify-between"><div><h4 className="dev-panel-section-title mb-0">10 Color Palettes</h4><p className="text-[10px] text-slate-400">Klik palette untuk mengganti seluruh warna theme secara otomatis.</p></div><Palette className="h-4 w-4 text-slate-400"/></div><div className="dev-panel-palette mt-4">{colorPalettes.map(p=><button key={p.id} type="button" onClick={()=>applyPalette(p)} className="dev-panel-palette-button"><span className="dev-panel-swatch" style={{background:`linear-gradient(135deg,${p.colors.primaryColor} 0 48%,${p.colors.accentColor} 48% 100%)`}}/><span className="truncate text-[10px] font-bold text-slate-700">{p.name}</span><span className="text-[8px] text-slate-400">Primary + Accent</span></button>)}</div></section>
  <section className="dev-panel-section"><h4 className="dev-panel-section-title">Theme Colors</h4><div className="dev-panel-grid">{(['primaryColor','primaryHover','secondaryColor','accentColor','backgroundColor','surfaceColor','textColor','mutedTextColor','whatsappColor'] as const).filter(k=>k in theme).map(k=><Field key={k} label={k} value={(theme as AnyRecord)[k]||''} path={[k]} onChange={(p,v)=>onChange(setPath(theme,p,v))}/>)}</div></section>
  <section className="dev-panel-section"><h4 className="dev-panel-section-title">Typography & Shape</h4><div className="dev-panel-grid">{(['fontOptionId','fontFamily','fontHeading','fontBody','borderRadius','heroVariant'] as const).filter(k=>k in theme).map(k=><Field key={k} label={k} value={(theme as AnyRecord)[k]||''} path={[k]} onChange={(p,v)=>onChange(setPath(theme,p,v))}/>)}</div></section>
 </div>;
}

function LayoutMini({id}:{id:HeroLayoutVariant}){
 const center=id==='centered'||id==='spotlight'||id==='editorial'; const reverse=id==='card-right'; const full=['background-focus','floating-card','bottom-bar'].includes(id); return <div className={`dev-panel-mini-preview ${center?'center':''} ${reverse?'reverse':''} ${full?'full':''}`}><span className="left a"/><span className="right b"/><span className="c"/></div>;
}

function HeroEditor({hero,onChange}:{hero:HeroConfig;onChange:(h:HeroConfig)=>void}){
 const patch=(p:Partial<HeroConfig>)=>onChange({...hero,...p});
 const applyLayout=(id:HeroLayoutVariant)=>{const preset=heroVariantPresets[id];onChange({...hero,...preset,layoutVariant:id,headline:hero.headline,description:hero.description,primaryCtaText:hero.primaryCtaText,secondaryCtaText:hero.secondaryCtaText,backgroundImageUrl:hero.backgroundImageUrl});};
 return <div className="space-y-4">
  <section className="dev-panel-section"><div className="mb-3"><h4 className="dev-panel-section-title mb-0">10 Opsi Layout Hero</h4><p className="text-[10px] text-slate-400">Preset sekarang mengubah <b>layoutVariant + style</b> hero sekaligus, sehingga perubahan langsung terlihat pada live hero.</p></div><div className="dev-panel-layout-grid">{heroLayoutOptions.map(o=><button key={o.id} type="button" onClick={()=>applyLayout(o.id)} className={`dev-panel-layout-card ${hero.layoutVariant===o.id?'is-active':''}`}><LayoutMini id={o.id}/><div className="flex items-center justify-between gap-2"><b className="text-[10px] text-slate-800">{o.name}</b>{hero.layoutVariant===o.id&&<Check className="h-3.5 w-3.5 shrink-0 text-sky-600"/>}</div><p className="mt-1 text-[9px] font-medium text-slate-500">{o.subtitle}</p><p className="mt-1 text-[9px] leading-4 text-slate-400">{o.description}</p></button>)}</div></section>
  <section className="dev-panel-section"><h4 className="dev-panel-section-title">Copywriting & CTA</h4><div className="space-y-3">{[['Eyebrow Text','eyebrowText'],['Badge Text','badgeText'],['Headline','headline'],['Description','description'],['Primary CTA Text','primaryCtaText'],['Primary CTA URL','primaryCtaUrl'],['Secondary CTA Text','secondaryCtaText'],['Secondary CTA URL','secondaryCtaUrl'],['CTA Note','ctaNote']].map(([l,k])=><Field key={k} label={l} value={(hero as AnyRecord)[k]||''} path={[k]} onChange={(p,v)=>patch(setPath(hero,p,v))}/>)}</div></section>
  <section className="dev-panel-section"><h4 className="dev-panel-section-title">Trust & Social Proof</h4><div className="space-y-3"><Field label="Trust Badge Text" value={hero.trustBadgeText||''} path={['trustBadgeText']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Trust Points" value={hero.trustPoints||[]} path={['trustPoints']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><div className="dev-panel-grid"><Field label="Rating Value" value={hero.ratingValue||''} path={['ratingValue']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Rating Label" value={hero.ratingLabel||''} path={['ratingLabel']} onChange={(p,v)=>patch(setPath(hero,p,v))}/></div><Field label="Show Trust Points" value={hero.showTrustPoints??true} path={['showTrustPoints']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Show Rating Pill" value={hero.showRatingPill??true} path={['showRatingPill']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Show Floating Stats" value={hero.showFloatingStats??false} path={['showFloatingStats']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Floating Stats" value={hero.floatingStats||[]} path={['floatingStats']} onChange={(p,v)=>patch(setPath(hero,p,v))}/></div></section>
  <section className="dev-panel-section"><h4 className="dev-panel-section-title">Background & Contrast</h4><div className="dev-panel-grid">{heroBackgroundOptions.map(o=><button key={o.id} type="button" onClick={()=>patch({backgroundType:o.id})} className={`rounded-xl border p-3 text-left text-[10px] font-bold ${hero.backgroundType===o.id?'border-violet-600 bg-violet-50':'border-slate-200 bg-white hover:border-slate-300'}`}>{o.name}<span className="mt-1 block text-[8px] font-normal text-slate-400">{o.description}</span></button>)}</div><div className="mt-3 space-y-3"><div className="dev-panel-grid"><Field label="Background Color" value={hero.backgroundColor||'#FFFFFF'} path={['backgroundColor']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Background Image URL" value={hero.backgroundImageUrl||''} path={['backgroundImageUrl']} onChange={(p,v)=>patch(setPath(hero,p,v))}/></div><div className="dev-panel-grid"><Field label="Background Image Alt" value={hero.backgroundImageAlt||''} path={['backgroundImageAlt']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Background Image Opacity" value={hero.backgroundImageOpacity??.34} path={['backgroundImageOpacity']} onChange={(p,v)=>patch(setPath(hero,p,v))}/></div><div className="dev-panel-grid"><Field label="Overlay Color" value={hero.overlayColor||'#0B0F19'} path={['overlayColor']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Overlay Opacity" value={hero.overlayOpacity??.68} path={['overlayOpacity']} onChange={(p,v)=>patch(setPath(hero,p,v))}/></div><Field label="Overlay Gradient" value={hero.overlayGradient??true} path={['overlayGradient']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Text Theme" value={hero.textTheme||'auto'} path={['textTheme']} onChange={(p,v)=>patch(setPath(hero,p,v))}/></div></section>
  <section className="dev-panel-section"><h4 className="dev-panel-section-title">Gradient & Layout Detail</h4><div className="dev-panel-grid">{heroGradientOptions.map(o=><button key={o.id} type="button" onClick={()=>patch({gradientStyle:o.id,backgroundMode:o.suggestedMode})} className={`rounded-xl border p-2.5 text-left text-[9px] font-bold ${hero.gradientStyle===o.id?'border-amber-500 bg-amber-50':'border-slate-200 bg-white'}`}><span className="mb-2 block h-2 rounded" style={{background:`linear-gradient(90deg,${o.previewColors.join(',')})`}}/>{o.name}</button>)}</div><div className="mt-3 dev-panel-grid"><Field label="Background Mode" value={hero.backgroundMode||'auto'} path={['backgroundMode']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Texture" value={hero.texture||'none'} path={['texture']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Texture Opacity" value={hero.textureOpacity??.04} path={['textureOpacity']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Content Align" value={hero.contentAlign||'left'} path={['contentAlign']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Content Max Width" value={hero.contentMaxWidth||'lg'} path={['contentMaxWidth']} onChange={(p,v)=>patch(setPath(hero,p,v))}/><Field label="Min Height" value={hero.minHeight||'large'} path={['minHeight']} onChange={(p,v)=>patch(setPath(hero,p,v))}/></div></section>
  <section className="dev-panel-section"><h4 className="dev-panel-section-title">Quick Background Presets</h4><div className="dev-panel-grid">{heroBackgroundPresets.map(p=><button key={p.name} type="button" onClick={()=>patch({backgroundColor:p.color,backgroundMode:p.isDark?'dark':'light',textTheme:p.isDark?'light':'dark',overlayColor:p.isDark?p.color:'#FFFFFF'})} className="rounded-xl border border-slate-200 bg-white p-3 text-left text-[9px] font-semibold hover:border-slate-300"><span className="mr-2 inline-block h-5 w-5 rounded-full border align-middle" style={{backgroundColor:p.color}}/>{p.name}</button>)}</div></section>
 </div>;
}

export const DevPanel:React.FC<DevPanelProps>=({currentBusiness,onSelectBusiness})=>{
 const [open,setOpen]=useState(false); const [tab,setTab]=useState<Tab>('business'); const [msg,setMsg]=useState('');
 const hero:HeroConfig={...heroVariantPresets['card-left'],...(currentBusiness.hero||{}),headline:currentBusiness.hero?.headline||currentBusiness.heroHeadline,description:currentBusiness.hero?.description||currentBusiness.heroDescription,primaryCtaText:currentBusiness.hero?.primaryCtaText||currentBusiness.primaryCtaText,secondaryCtaText:currentBusiness.hero?.secondaryCtaText||currentBusiness.secondaryCtaText,backgroundImageUrl:currentBusiness.hero?.backgroundImageUrl||currentBusiness.heroImageUrl};
 const change=(next:BusinessConfig)=>onSelectBusiness(next); const flash=(s:string)=>{setMsg(s);window.setTimeout(()=>setMsg(''),2200);};
 const active=tab==='business'?Object.fromEntries(businessFields.map(k=>[k,(currentBusiness as AnyRecord)[k]])):((currentBusiness as AnyRecord)[configKeys[tab as Exclude<Tab,'business'>]]||{});
 const onChange=(path:string[],value:any)=>{const key=tab==='business'?null:configKeys[tab as Exclude<Tab,'business'>];if(key) change(setPath(currentBusiness,[String(key),...path],value)); else change(setPath(currentBusiness,path,value));};
 const onDelete=(path:string[])=>{const key=tab==='business'?null:configKeys[tab as Exclude<Tab,'business'>];if(key) change(delPath(currentBusiness,[String(key),...path])); else change(delPath(currentBusiness,path));};
 const selectTemplate=(id:string)=>{const found=templateList.find(t=>t.id===id);if(!found)return;const next=JSON.parse(JSON.stringify(found.template)) as BusinessConfig;next.hero={...(next.hero||{}),...heroVariantPresets[found.heroVariant],layoutVariant:found.heroVariant,headline:next.hero?.headline||next.heroHeadline,description:next.hero?.description||next.heroDescription,primaryCtaText:next.hero?.primaryCtaText||next.primaryCtaText,secondaryCtaText:next.hero?.secondaryCtaText||next.secondaryCtaText,backgroundImageUrl:next.hero?.backgroundImageUrl||next.heroImageUrl};change(next);setTab('business');flash(`Preset ${found.name} diterapkan`);};
 const exportAll=()=>{const content=`import { BusinessConfig } from '../types/business';\n\nexport const businessConfig: BusinessConfig = ${JSON.stringify(currentBusiness,null,2)};\n\nexport default businessConfig;\n`;download(`${currentBusiness.id}-business.config.ts`,content);flash('Full config berhasil dibuat');};
 return <div className="dev-panel-shell"><button type="button" onClick={()=>setOpen(true)} className="fixed right-4 top-4 z-[100] flex items-center gap-2 rounded-full border border-slate-700 bg-slate-950 px-4 py-2.5 text-xs font-semibold text-white shadow-2xl"><Settings2 className="h-3.5 w-3.5 text-amber-400"/>Config Generator<span className="hidden sm:inline text-amber-300">· {currentBusiness.name}</span></button>
 {open&&<div className="dev-panel-overlay"><button aria-label="Tutup" onClick={()=>setOpen(false)} className="absolute inset-0"/><aside className="dev-panel-drawer"><header className="dev-panel-header"><div><div className="flex items-center gap-2 text-sm font-bold"><Sparkles className="h-4 w-4 text-amber-400"/>UMKM Config Generator</div><p className="mt-1 text-[10px] text-slate-400">Preset bisnis · Theme · Hero · Content config</p></div><button type="button" onClick={()=>setOpen(false)} className="rounded-lg p-2 hover:bg-white/10"><X className="h-4 w-4"/></button></header><div className="dev-panel-body"><nav className="dev-panel-sidebar dev-panel-scrollbar">{groups.map(g=><div key={g.title} className="mb-5"><p className="mb-2 px-2 text-[8px] font-black uppercase tracking-[.16em] text-slate-400">{g.title}</p>{g.items.map(([id,label,Icon])=><button key={id} type="button" onClick={()=>setTab(id as Tab)} className={`mb-1 flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-left text-[10px] font-bold transition ${tab===id?'bg-slate-900 text-white shadow-sm':'text-slate-600 hover:bg-white hover:text-slate-900'}`}><Icon className="h-3.5 w-3.5"/>{label}</button>)}</div>)}<button type="button" onClick={()=>{const t=templateList.find(x=>x.template.id===currentBusiness.id)?.template;if(t){change(JSON.parse(JSON.stringify(t)));flash('Preset saat ini direset');}}} className="flex w-full items-center gap-2 rounded-xl px-3 py-2.5 text-[10px] font-bold text-slate-500 hover:bg-white"><RotateCcw className="h-3.5 w-3.5"/>Reset preset</button></nav><main className="dev-panel-content dev-panel-scrollbar"><div className="mb-5 flex items-start justify-between gap-4"><div><p className="mb-1 text-[9px] font-black uppercase tracking-[.16em] text-sky-600">Configuration</p><h3 className="text-lg font-black tracking-tight text-slate-900">{labels[tab]}</h3><p className="mt-1 max-w-2xl text-[10px] leading-5 text-slate-400">{tab==='hero'?'Pilih layout, atur visual, dan lihat perubahan hero secara langsung di halaman.':tab==='theme'?'Gunakan palette siap pakai atau ubah warna satu per satu.':'Edit nilai config tanpa menyentuh komponen UI.'}</p></div>{tab==='hero'&&<button type="button" onClick={()=>change({...currentBusiness,hero:{...heroVariantPresets['card-left'],headline:currentBusiness.heroHeadline,description:currentBusiness.heroDescription,primaryCtaText:currentBusiness.primaryCtaText,secondaryCtaText:currentBusiness.secondaryCtaText,backgroundImageUrl:currentBusiness.heroImageUrl}})} className="shrink-0 rounded-xl border border-slate-200 bg-white px-3 py-2 text-[9px] font-bold text-slate-700 hover:bg-slate-50">Reset Hero</button>}</div>
 {tab==='business'&&<section className="dev-panel-section mb-4 border-sky-100 bg-sky-50/60"><div className="mb-3 flex items-center gap-2"><div className="rounded-xl bg-white p-2 shadow-sm"><Store className="h-4 w-4 text-sky-700"/></div><div><h4 className="dev-panel-section-title mb-0">Preset Bisnis UMKM</h4><p className="text-[10px] text-slate-500">Pilih tipe usaha untuk memulai dari config realistis.</p></div></div><div className="dev-panel-preset-grid">{templateList.map(t=><button key={t.id} type="button" onClick={()=>selectTemplate(t.id)} className={`dev-panel-preset ${currentBusiness.id===t.template.id?'is-active':''}`}><div className="flex items-center justify-between"><b className="text-[10px] text-slate-900">{t.name}</b>{currentBusiness.id===t.template.id&&<Check className="h-3.5 w-3.5 text-sky-600"/>}</div><p className="mt-1 text-[9px] font-semibold text-slate-400">{t.category}</p><p className="mt-1.5 text-[9px] leading-4 text-slate-500">{t.description}</p><span className="mt-2 inline-block rounded-full px-2 py-1 text-[8px] font-bold" style={{backgroundColor:`${t.accentColor}14`,color:t.accentColor}}>Hero: {t.heroVariant}</span></button>)}</div></section>}
 {tab==='theme'&&<ThemeEditor theme={currentBusiness.theme} onChange={theme=>change({...currentBusiness,theme})}/>} {tab==='hero'&&<HeroEditor hero={hero} onChange={h=>change({...currentBusiness,hero:h})}/>} {tab!=='business'&&tab!=='theme'&&tab!=='hero'&&<div className="dev-panel-section"><div className="space-y-3">{Object.entries(active).map(([k,v])=><Field key={k} label={k} value={v} path={[k]} onChange={onChange} onDelete={onDelete}/>)}</div></div>} {tab==='business'&&<div className="dev-panel-section"><div className="space-y-3">{Object.entries(active).map(([k,v])=><Field key={k} label={k} value={v} path={[k]} onChange={onChange} onDelete={onDelete}/>)}</div></div>}
 </main></div><footer className="dev-panel-footer"><button type="button" onClick={exportAll} className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-3.5 py-2.5 text-[9px] font-bold text-white shadow-sm"><Download className="h-3 w-3"/>Generate Full Config</button><button type="button" onClick={()=>{navigator.clipboard.writeText(JSON.stringify(currentBusiness,null,2));flash('JSON tersalin')}} className="inline-flex items-center gap-1.5 rounded-xl border border-slate-200 bg-white px-3.5 py-2.5 text-[9px] font-bold text-slate-700"><Copy className="h-3 w-3"/>Copy JSON</button>{msg&&<span className="dev-panel-status">{msg}</span>}</footer></aside></div>}
 </div>;
};

function download(name:string,content:string){const blob=new Blob([content],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
