import React, { useEffect, useState } from 'react';
import { BusinessConfig } from '../types/business';
import { generateWhatsAppLink } from '../lib/whatsapp';
import { DynamicIcon } from '../lib/icons';
import { Menu, X, Phone, Clock, ChevronDown } from 'lucide-react';
import { WhatsAppIcon } from './common/WhatsAppIcon';

interface NavbarProps { business: BusinessConfig; }

export const Navbar: React.FC<NavbarProps> = ({ business }) => {
  const [isScrolled,setIsScrolled]=useState(false); const [mobileMenuOpen,setMobileMenuOpen]=useState(false); const [moreOpen,setMoreOpen]=useState(false);
  useEffect(()=>{const onScroll=()=>setIsScrolled(window.scrollY>20);window.addEventListener('scroll',onScroll);return()=>window.removeEventListener('scroll',onScroll);},[]);
  useEffect(()=>{setMoreOpen(false);setMobileMenuOpen(false);},[business.id]);
  const fallbackLinks=[{name:'Beranda',href:'#beranda',show:true},{name:'Tentang',href:'#tentang',show:business.sections?.about!==false},{name:'Layanan',href:'#layanan',show:business.sections?.services!==false},{name:'Paket Biaya',href:'#harga',show:business.sections?.pricing!==false},{name:'Keunggulan',href:'#keunggulan',show:business.sections?.whyChooseUs!==false},{name:'Galeri',href:'#galeri',show:business.sections?.gallery!==false},{name:'Testimoni',href:'#testimoni',show:business.sections?.testimonials!==false},{name:'Lokasi & Jam',href:'#lokasi',show:business.sections?.location!==false},{name:'FAQ',href:'#faq',show:business.sections?.faq!==false}];
  const configured=(business.navigation?.links||[]).map(l=>({...l,show:l.showInTopNav!==false})); const source=configured.length?configured:fallbackLinks; const navLinks=source.filter(l=>l.show); const maxVisible=Math.max(3,business.navigation?.topNavMaxVisible||5); const visibleLinks=navLinks.slice(0,maxVisible); const overflowLinks=navLinks.slice(maxVisible);
  const waLink=generateWhatsAppLink(business.contact.whatsappNumber,business.contact.defaultWhatsAppMessage); const ctaText=business.navigation?.ctaButtonText||business.hero?.primaryCtaText||business.primaryCtaText;
  return <>
    {business.navigation?.showTopMicroBar!==false&&<div className="w-full bg-slate-950 px-4 py-1.5 text-xs text-white"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-1 sm:flex-row"><div className="flex items-center gap-4 text-slate-300"><span className="flex items-center gap-1.5"><Clock className="h-3.5 w-3.5 text-emerald-400"/><span>Buka: {business.openingHours?.[0]?.hours||'08.00 - 17.00 WIB'}</span></span><span className="hidden md:inline text-slate-500">•</span><span className="hidden md:flex">{business.contact.city}, {business.contact.province}</span></div><a href={`tel:${business.contact.phone.replace(/\D/g,'')}`} className="flex items-center gap-1 text-slate-300 hover:text-white"><Phone className="h-3 w-3 text-emerald-400"/>{business.contact.phone}</a></div></div>}
    <header className={`sticky top-0 z-40 border-b border-slate-200/70 transition-all duration-200 ${isScrolled?'bg-white/95 py-2.5 shadow-[0_6px_24px_rgba(15,23,42,0.10)] backdrop-blur-xl':'bg-white/95 py-3.5 shadow-[0_2px_14px_rgba(15,23,42,0.06)] backdrop-blur-md'}`}>
      <div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 sm:px-6 lg:px-8">
        <a href="#beranda" className="flex min-w-0 shrink-0 items-center gap-3 group"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl text-lg font-bold text-white shadow-sm transition-transform group-hover:scale-105" style={{backgroundColor:business.theme.primaryColor}}><DynamicIcon name="Wrench" className="h-5 w-5 text-white"/></div><div className="min-w-0"><span className="block truncate text-lg font-bold leading-none tracking-tight text-slate-900 sm:text-xl">{business.navigation?.brandName||business.name}</span><span className="mt-0.5 block truncate text-[11px] font-medium uppercase tracking-wide text-slate-500">{business.navigation?.brandSubtitle||business.industry}</span></div></a>
        <nav className="hidden min-w-0 flex-1 items-center justify-center gap-x-4 xl:flex 2xl:gap-x-5">{visibleLinks.map(link=><a key={link.name} href={link.href} className="whitespace-nowrap rounded-lg px-2 py-1.5 text-sm font-medium text-slate-600 transition-all hover:bg-slate-50 hover:text-slate-900">{link.name}</a>)}{overflowLinks.length>0&&<div className="relative shrink-0"><button type="button" onClick={()=>setMoreOpen(v=>!v)} className="inline-flex items-center gap-1 whitespace-nowrap rounded-lg px-2 py-1.5 text-sm font-semibold text-slate-600 hover:bg-slate-50 hover:text-slate-900">Lainnya<ChevronDown className={`h-4 w-4 transition-transform ${moreOpen?'rotate-180':''}`}/></button>{moreOpen&&<div className="absolute right-0 top-full z-50 mt-2 min-w-48 rounded-xl border border-slate-200 bg-white p-1.5 shadow-xl">{overflowLinks.map(link=><a key={link.name} href={link.href} onClick={()=>setMoreOpen(false)} className="block rounded-lg px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">{link.name}</a>)}</div>}</div>}</nav>
        <div className="hidden shrink-0 lg:flex items-center gap-3"><a id="navbar-wa-cta" href={waLink} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md" style={{backgroundColor:business.theme.primaryColor}}><WhatsAppIcon className="h-4 w-4"/><span>{ctaText}</span></a></div>
        <button id="mobile-menu-toggle" type="button" onClick={()=>setMobileMenuOpen(!mobileMenuOpen)} className="rounded-xl p-2 text-slate-700 transition-colors hover:bg-slate-100 xl:hidden" aria-label="Buka Menu">{mobileMenuOpen?<X className="h-6 w-6"/>:<Menu className="h-6 w-6"/>}</button>
      </div>
    </header>
    {mobileMenuOpen&&<div className="fixed inset-0 z-50 xl:hidden"><button aria-label="Tutup menu" className="fixed inset-0 bg-slate-900/60 backdrop-blur-sm" onClick={()=>setMobileMenuOpen(false)}/><div className="fixed inset-y-0 right-0 flex w-full max-w-xs flex-col justify-between overflow-y-auto bg-white p-6 shadow-2xl"><div><div className="flex items-center justify-between border-b border-slate-100 pb-4"><div className="flex min-w-0 items-center gap-2.5"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-white" style={{backgroundColor:business.theme.primaryColor}}><DynamicIcon name="Wrench" className="h-4 w-4"/></div><span className="truncate text-base font-bold text-slate-900">{business.navigation?.brandName||business.name}</span></div><button type="button" onClick={()=>setMobileMenuOpen(false)} className="rounded-lg p-1.5 text-slate-500 hover:bg-slate-100"><X className="h-5 w-5"/></button></div><div className="space-y-1 py-4">{navLinks.map(link=><a key={link.name} href={link.href} onClick={()=>setMobileMenuOpen(false)} className="block rounded-lg px-3 py-2.5 text-base font-medium text-slate-700 hover:bg-slate-50">{link.name}</a>)}</div></div><div className="space-y-3 border-t border-slate-100 pt-4"><a href={waLink} target="_blank" rel="noopener noreferrer" onClick={()=>setMobileMenuOpen(false)} className="flex w-full items-center justify-center gap-2 rounded-xl px-4 py-3 font-semibold text-white shadow-md" style={{backgroundColor:business.theme.primaryColor}}><WhatsAppIcon className="h-5 w-5"/>{ctaText}</a><a href={`tel:${business.contact.phone.replace(/\D/g,'')}`} className="flex w-full items-center justify-center gap-2 rounded-xl bg-slate-100 px-4 py-2.5 text-sm font-medium text-slate-700"><Phone className="h-4 w-4"/>Telepon: {business.contact.phone}</a></div></div></div>}
  </>;
};
